# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 
email: 
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thelab.dc.gov" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

timezone: America/New_York

# Folder Structure
source: ./source

contentful:
  spaces:
    - people: # Jekyll _data folder identifier - Required
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: / # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: people

    - jobs: # Jekyll _data folder identifier - Required
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source         # Optional - Defaults to Current directory
        destination: / # Optional - Defaults to _data/contentful/spaces
        all_entries: true
        cda_query:
          content_type: jobPostings

# sass_dir: source/css

page_gen:
  - data: 'people.people'
    template: 'team'
    name: 'firstName'
    dir: '/'
