name: Build and Deploy Website
on:
  push:
    branches:
      - source
  repository_dispatch:
    types:
      - contentful_push

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - name: Pull cache if available
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-use-ruby-2.4-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-2.4-

      - name: bundle install
        run: |
          gem install bundler:1.17.3
          bundle config deployment true
          bundle config path vendor/bundle
          bundle install --jobs 4

      - name: Pull content from contentful
        run: bundle exec jekyll contentful
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

      - name: Build the page
        run: bundle exec jekyll build

      - name: Push to GH Pages
        uses: JamesIves/github-pages-deploy-action@3.5.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: source
          FOLDER: _site
